version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: visitor-map:latest
    container_name: visitor-map-app
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/visitors.db
      - IP_SALT=change-me-in-prod
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/data
    restart: unless-stopped

volumes:
  db-data: {}
