import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import "leaflet/dist/leaflet.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="sticky top-0 z-50 border-b border-black/10 dark:border-white/10 backdrop-blur bg-background/80">
          <nav className="mx-auto max-w-7xl px-6 py-4 flex items-center justify-between">
            <Link href="/" className="font-semibold tracking-tight">Visitor Map</Link>
            <div className="flex items-center gap-6 text-sm">
              <Link href="/" className="hover:underline">Map</Link>
              <Link href="/stats" className="hover:underline">Stats</Link>
            </div>
          </nav>
        </header>
        <main className="mx-auto max-w-7xl px-6 py-8 min-h-[calc(100vh-56px)]">{children}</main>
        <footer className="border-t border-black/10 dark:border-white/10 py-6 text-center text-xs text-foreground/70">
          © {new Date().getFullYear()} Visitor Map
        </footer>
      </body>
    </html>
  );
}
